## YAML Template.
version: "3.7"
services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3309:3306"
        volumes:
            - /C/Users/oscar/Documents/CLASES ALCALA/2019-2020/dam2_2019/accesoDatos/mysqlDocker/mysql-data:/var/lib/mysql
       
    
