## YAML Template.
version: "3.7"
services:
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3309:3306"
        volumes:
            - ${DATA}:/var/lib/mysql
       
    
