## YAML Template.
---
user: kiko
pass: kiko
casas:
  - azul
  - verde
  - gris
recetas:
  tortilla: huevos verdes
  risotto: arroz
usuarios:
  - name: juan
    pass: juan
    direccion: kk
  - name: pedro
    pass: pedro